workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "io.codemagic.sample.androidnative"
    scripts:
      - name: Permissão ao Gradlew
        script: chmod +x ./gradlew
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Test
        script: |
          set -e
          ./gradlew test
      - name: Buildando Apk
        script: |
          ./gradlew assembleDebug
      - name: Buildando AAB
        script: |
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - sacconrenan@gmail.com
        notify:
          success: true
          failure: true


    


